[tools]
uv = "latest"

[env]
FLASK_APP = "app.py"
# API keys (must be set in environment or mise.local.toml)
WHATSAPP_TOKEN = { required = true }
VERIFY_TOKEN = { required = true }
VAPI_TOKEN = { required = true }
CUSTOMER_NUMBER = { required = true }
STEDI_API_KEY = { required = true }

[tasks.dev]
description = "run the app in debug mode"
run = "flask run --debug"

[tasks.prod]
description = "run the app in prod mode"
run = "flask run --host 0.0.0.0 --port 9000 --no-debugger --no-reload"