[project]
name = "babycomeback"
version = "0.1.0"
description = "OOP Hackathon"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
